window.GAMES=[
{id:"tictactoe",name:"Tic-Tac-Toe",cat:"Classic",icon:"\u274c",desc:"Lawan bot sederhana. Dapatkan 3 simbol berurutan.",init:Games.tic},
{id:"rps",name:"Rock Paper Scissors",cat:"Classic",icon:"\u270a",desc:"Pilih batu, kertas, atau gunting.",init:Games.rps},
{id:"connect4",name:"Connect Four",cat:"Strategy",icon:"\ud83d\udd34",desc:"Jatuhkan keping dan sambungkan empat.",init:Games.connect},
{id:"memory",name:"Memory Cards",cat:"Puzzle",icon:"\ud83e\udde0",desc:"Cari semua pasangan kartu.",init:Games.memory},
{id:"snake",name:"Snake",cat:"Arcade",icon:"\ud83d\udc0d",desc:"Makan makanan dan jangan menabrak.",init:Games.snake},
{id:"g2048",name:"2048",cat:"Puzzle",icon:"\ud83d\udd22",desc:"Gabungkan angka hingga setinggi mungkin.",init:Games.2048},
{id:"minesweeper",name:"Minesweeper",cat:"Puzzle",icon:"\ud83d\udca3",desc:"Buka sel aman dan hindari ranjau.",init:Games.mine},
{id:"flappy",name:"Flappy Bird",cat:"Arcade",icon:"\ud83d\udc26",desc:"Lewati pipa sebanyak mungkin.",init:Games.flappy},
{id:"breakout",name:"Breakout",cat:"Arcade",icon:"\ud83e\uddf1",desc:"Hancurkan semua blok dengan bola.",init:Games.break},
{id:"pong",name:"Pong",cat:"Classic",icon:"\ud83c\udfd3",desc:"Pantulkan bola melewati paddle bot.",init:Games.pong},
{id:"whack",name:"Whack-a-Mole",cat:"Quick",icon:"\ud83d\udd28",desc:"Pukul target secepat mungkin.",init:Games.whack},
{id:"reaction",name:"Reaction Test",cat:"Quick",icon:"\u26a1",desc:"Klik saat layar berubah.",init:Games.reaction},
{id:"guess",name:"Number Guess",cat:"Quick",icon:"\ud83c\udfaf",desc:"Tebak angka rahasia 1-100.",init:Games.guess},
{id:"hangman",name:"Hangman",cat:"Puzzle",icon:"\ud83d\udd24",desc:"Tebak kata sebelum kesempatan habis.",init:Games.hang},
{id:"scramble",name:"Word Scramble",cat:"Puzzle",icon:"\ud83d\udcdd",desc:"Susun kembali huruf yang diacak.",init:Games.scramble},
{id:"math",name:"Math Challenge",cat:"Quick",icon:"\u2797",desc:"Jawab soal matematika dengan cepat.",init:Games.math},
{id:"simon",name:"Simon Says",cat:"Quick",icon:"\ud83d\udfe2",desc:"Ikuti urutan tombol yang menyala.",init:Games.simon},
{id:"lights",name:"Lights Out",cat:"Puzzle",icon:"\ud83d\udca1",desc:"Matikan semua lampu.",init:Games.lights},
{id:"sudoku",name:"Mini Sudoku",cat:"Puzzle",icon:"\ud83e\udde9",desc:"Isi grid 4x4 tanpa angka kembar.",init:Games.sudoku},
{id:"sliding",name:"Sliding Puzzle",cat:"Puzzle",icon:"\ud83d\udd32",desc:"Susun angka 1-8.",init:Games.slide},
{id:"maze",name:"Maze",cat:"Puzzle",icon:"\ud83c\udf00",desc:"Cari jalan dari START ke GOAL.",init:Games.maze},
{id:"tap",name:"Tap Speed",cat:"Quick",icon:"\ud83d\udc46",desc:"Tap tombol sebanyak mungkin dalam 10 detik.",init:Games.tap},
{id:"color",name:"Color Match",cat:"Quick",icon:"\ud83c\udfa8",desc:"Klik warna yang sesuai dengan kata target.",init:Games.color},
{id:"quick",name:"Quick Click",cat:"Quick",icon:"\ud83d\uddb1\ufe0f",desc:"Klik target yang berpindah.",init:Games.quick},
{id:"coin",name:"Coin Flip",cat:"Classic",icon:"\ud83e\ude99",desc:"Prediksi hasil lemparan koin.",init:Games.coin},
{id:"dice",name:"Dice Roller",cat:"Classic",icon:"\ud83c\udfb2",desc:"Tebak hasil dadu 1-6.",init:Games.dice},
{id:"higher",name:"Higher or Lower",cat:"Cards",icon:"\u2b06\ufe0f",desc:"Tebak kartu berikutnya lebih tinggi/rendah.",init:Games.higher},
{id:"cards",name:"Twenty-One",cat:"Cards",icon:"\ud83c\udccf",desc:"Dekati 21 tanpa melewatinya.",init:Games.blackjack},
{id:"runner",name:"Endless Runner",cat:"Arcade",icon:"\ud83c\udfc3",desc:"Lompat melewati rintangan.",init:Games.runner},
{id:"space",name:"Space Shooter",cat:"Arcade",icon:"\ud83d\ude80",desc:"Hancurkan musuh yang datang.",init:Games.space}
];
window.Games={};
const $=s=>document.querySelector(s);
function btn(t,fn){let b=document.createElement('button');b.className='bigbtn';b.textContent=t;b.onclick=fn;return b}
Games.tic=(el,set)=>{el.innerHTML='<div><div id="tb" class="board" style="grid-template-columns:repeat(3,70px)"></div><p class="msg" id="tm"></p></div>';let b=Array(9).fill(''),turn='X',over=0;let wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];function draw(){let x=$('#tb');x.innerHTML='';b.forEach((v,i)=>{let q=btn(v||'·',()=>move(i));q.className='cell';x.append(q)});if(!over)$('#tm').textContent='Giliranmu: X'}function move(i){if(over||b[i])return;b[i]='X';check();if(!over){let z=b.map((v,i)=>v?'':i).filter(x=>x!==''),k=z[Math.floor(Math.random()*z.length)];if(k!==undefined){b[k]='O';check()}}draw()}function check(){let w=wins.find(x=>b[x[0]]&&b[x[0]]===b[x[1]]&&b[x[1]]===b[x[2]]);if(w){over=1;set(b[w[0]]==='X'?100:20);$('#tm').textContent=b[w[0]]==='X'?'Menang!':'Bot menang.'}else if(b.every(Boolean)){over=1;$('#tm').textContent='Seri.'}}draw()};
Games.rps=(el,set)=>{el.innerHTML='<div style="text-align:center"><h3>Pilih gerakan</h3><div id="rp"></div><p class="msg" id="rm"></p></div>';let arr=[['✊','Batu'],['✋','Kertas'],['✌️','Gunting']];arr.forEach((x,i)=>{let b=btn(x[0]+' '+x[1],()=>{let c=Math.floor(Math.random()*3),r=(i-c+3)%3;set(r===0?0:r===1?100:20);$('#rm').textContent=`Bot: ${arr[c][1]} — ${r===0?'Seri':r===1?'Kamu menang!':'Kamu kalah.'}`});$('#rp').append(b)})};
Games.connect=(el,set)=>{el.innerHTML='<div><div id="cb" class="board" style="grid-template-columns:repeat(7,42px)"></div><p class="msg" id="cm">Kamu 🔴</p></div>';let a=Array(42).fill(''),over=0;function win(p){for(let r=0;r<6;r++)for(let c=0;c<7;c++){let i=r*7+c;if(a[i]!==p)continue;for(let [dr,dc] of [[0,1],[1,0],[1,1],[1,-1]]){let n=1;for(let k=1;k<4;k++){let rr=r+dr*k,cc=c+dc*k;if(rr>=0&&rr<6&&cc>=0&&cc<7&&a[rr*7+cc]===p)n++;}if(n>=4)return 1}}return 0}function draw(){let x=$('#cb');x.innerHTML='';for(let i=0;i<42;i++){let q=btn(a[i]||'·',()=>drop(i%7));q.className='cell';q.style.width='42px';q.style.height='42px';x.append(q)}}function drop(c){if(over)return;for(let r=5;r>=0;r--){let i=r*7+c;if(!a[i]){a[i]='🔴';if(win('🔴')){over=1;set(150);$('#cm').textContent='Menang!'}else bot();draw();return}}}function bot(){let z=[];for(let c=0;c<7;c++)if(!a[c])z.push(c);let c=z[Math.floor(Math.random()*z.length)];for(let r=5;r>=0;r--){let i=r*7+c;if(!a[i]){a[i]='🟡';if(win('🟡')){over=1;$('#cm').textContent='Bot menang.'}break}}}draw()};
Games.memory=(el,set)=>{let vals=['🍎','🍋','🍇','🍉','🥝','🍒','🥕','🌽'];let a=[...vals,...vals].sort(()=>Math.random()-.5),open=[],done=0;el.innerHTML='<div style="width:min(600px,100%)"><div id="mb" class="gamegrid"></div><p class="msg" id="mm"></p></div>';function draw(){let b=$('#mb');b.innerHTML='';a.forEach((v,i)=>{let q=btn(open.includes(i)||done===8&&false?v:'?',()=>flip(i));q.style.fontSize='25px';b.append(q)});$('#mm').textContent=`Pasangan: ${done}/8`}function flip(i){if(open.includes(i)||open.length>=2||done===8)return;open.push(i);draw();if(open.length===2){if(a[open[0]]===a[open[1]]){done++;set(done*20);open=[];draw()}else setTimeout(()=>{open=[];draw()},500)}}draw()};
Games.snake=(el,set)=>{el.innerHTML='<div><canvas id="sc" width="320" height="320" style="max-width:100%;background:#080b12;border:2px solid #35405a"></canvas><p class="msg">Gunakan tombol panah/WASD. Di HP gunakan tombol di bawah.</p><div id="sd"></div></div>';let c=$('#sc'),x=c.getContext('2d'),s=20,body=[{x:8,y:8}],d={x:1,y:0},food={x:12,y:8},run=1,pts=0;let keys={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0],w:[0,-1],s:[0,1],a:[-1,0],d:[1,0]};onkeydown=e=>{if(keys[e.key]){let q=keys[e.key];if(q[0]!==-d.x||q[1]!==-d.y)d={x:q[0],y:q[1]}}};['↑','↓','←','→'].forEach((t,i)=>{let b=btn(t,()=>{let q=[[0,-1],[0,1],[-1,0],[1,0]][i];if(q[0]!==-d.x||q[1]!==-d.y)d={x:q[0],y:q[1]}});$('#sd').append(b)});function loop(){if(!run)return;let h={x:body[0].x+d.x,y:body[0].y+d.y};if(h.x<0||h.y<0||h.x>=16||h.y>=16||body.some(q=>q.x===h.x&&q.y===h.y)){run=0;return}body.unshift(h);if(h.x===food.x&&h.y===food.y){pts+=10;set(pts);food={x:Math.floor(Math.random()*16),y:Math.floor(Math.random()*16)}}else body.pop();x.clearRect(0,0,320,320);x.fillStyle='#65f5d2';body.forEach(q=>x.fillRect(q.x*s,q.y*s,s-2,s-2));x.fillStyle='#ff6384';x.fillRect(food.x*s,food.y*s,s-2,s-2);setTimeout(loop,110)}loop()};
Games['2048']=(el,set)=>{let a=Array(16).fill(0);el.innerHTML='<div><div id="24" class="gamegrid"></div><p class="msg">Gabungkan angka. Swipe tidak diperlukan: klik tombol arah.</p><div id="24c"></div></div>';function add(){let z=a.map((v,i)=>v?null:i).filter(x=>x!==null);if(z.length){a[z[Math.floor(Math.random()*z.length)]]=Math.random()<.9?2:4}}function draw(){let b=$('#24');b.innerHTML='';a.forEach(v=>{let q=btn(v||'',()=>{});q.style.fontSize='25px';b.append(q)})}function move(dir){let rows=[];for(let r=0;r<4;r++){let q=a.slice(r*4,r*4+4);if(dir==='up'||dir==='down'){q=a.filter((_,i)=>i%4===r)}rows.push(q)}if(dir==='right'||dir==='down')rows=rows.map(q=>q.reverse());let gain=0;rows=rows.map(q=>{q=q.filter(Boolean);for(let i=0;i<q.length-1;i++)if(q[i]===q[i+1]){q[i]*=2;gain+=q[i];q.splice(i+1,1)}while(q.length<4)q.push(0);return q});if(dir==='right'||dir==='down')rows=rows.map(q=>q.reverse());if(dir==='up'||dir==='down'){let n=Array(16).fill(0);for(let c=0;c<4;c++)for(let r=0;r<4;r++)n[r*4+c]=rows[c][r];a=n}else rows.flat().forEach((v,i)=>a[i]=v);if(gain)set(gain+(+$('#score').textContent||0));add();draw()}['←','→','↑','↓'].forEach((t,i)=>$('#24c').append(btn(t,()=>move(['left','right','up','down'][i]))));onkeydown=e=>({ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key]&&move({ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key]));add();add();draw()};
Games.mine=(el,set)=>{let n=25,mines=new Set();while(mines.size<5)mines.add(Math.floor(Math.random()*n));let open=new Set();el.innerHTML='<div><div id="mi" class="gamegrid"></div><p class="msg">Buka semua sel aman.</p></div>';function around(i){let r=Math.floor(i/5),c=i%5,z=0;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){let j=(r+dr)*5+c+dc;if(dr||dc)if(j>=0&&j<25&&Math.abs(j%5-c)<=1&&mines.has(j))z++}return z}function draw(){let b=$('#mi');b.innerHTML='';for(let i=0;i<n;i++){let q=btn(open.has(i)?(mines.has(i)?'💣':around(i)||'·'):'?',()=>click(i));b.append(q)}}function click(i){if(mines.has(i)){set(0);open=new Set([...Array(25).keys()]);draw();return}open.add(i);set(open.size*10);draw()}draw()};
Games.flappy=(el,set)=>{el.innerHTML='<div><canvas id="fc" width="360" height="260" style="max-width:100%;background:#10182b"></canvas><p class="msg">Klik/tap untuk terbang. Hindari pipa.</p></div>';let c=$('#fc'),x=c.getContext('2d'),y=120,v=0,score=0,pipes=[360],run=1;el.onclick=()=>v=-5;function loop(){if(!run)return;v+=.35;y+=v;pipes=pipes.map(p=>p-2).filter(p=>p>-40);if(!pipes.length||pipes[pipes.length-1]<210)pipes.push(360);x.clearRect(0,0,360,260);x.fillStyle='#65f5d2';x.fillRect(50,y,18,18);x.fillStyle='#8e7dff';pipes.forEach(p=>{let gap=90,top=40+(p%70);x.fillRect(p,0,35,top);x.fillRect(p,top+gap,35,260)});if(y<0||y>242||pipes.some(p=>50+18>p&&50<p+35&&(y<40+(p%70)||y+18>130+(p%70)))){run=0;return}score++;if(score%10===0)set(Math.floor(score/10));requestAnimationFrame(loop)}loop()};
Games.break=(el,set)=>simpleCanvas(el,set,'break');
Games.pong=(el,set)=>simpleCanvas(el,set,'pong');
Games.whack=(el,set)=>{let end=Date.now()+15000,pts=0;el.innerHTML='<div><div id="wh" class="gamegrid"></div><p class="msg">Klik target! 15 detik.</p></div>';function draw(){let b=$('#wh');b.innerHTML='';for(let i=0;i<25;i++)b.append(btn(i===target?'🔨':'·',()=>{if(i===target){pts++;set(pts);target=Math.floor(Math.random()*25);draw()}}))}let target=0;draw();let timer=setInterval(()=>{if(Date.now()>end){clearInterval(timer);$('#wh').innerHTML='<b>Waktu habis!</b>'}},200)};
Games.reaction=(el,set)=>{el.innerHTML='<div><button id="rx" class="bigbtn">Mulai</button><p class="msg" id="rmx"></p></div>';let t;$('#rx').onclick=()=>{let b=$('#rx');b.textContent='Tunggu...';b.disabled=true;setTimeout(()=>{t=performance.now();b.disabled=false;b.textContent='KLIK SEKARANG!';b.onclick=()=>{let ms=Math.round(performance.now()-t);set(Math.max(1,1000-ms));$('#rmx').textContent=`Waktu reaksi: ${ms} ms`;b.textContent='Coba lagi';b.onclick=()=>location.reload()}},1000+Math.random()*3000)}};
Games.guess=(el,set)=>{let n=Math.floor(Math.random()*100)+1,tries=0;el.innerHTML='<div><input id="gi" type="number" min="1" max="100" placeholder="1-100"><button class="bigbtn" id="gb">Tebak</button><p id="gm" class="msg"></p></div>';$('#gb').onclick=()=>{let v=+$('#gi').value;tries++;if(v===n){set(Math.max(10,100-tries*5));$('#gm').textContent=`Benar! Angkanya ${n}.`}else $('#gm').textContent=v<n?'Terlalu kecil.':'Terlalu besar.'}};
Games.hang=(el,set)=>wordGame(el,set,['JAVASCRIPT','ROBOT','KOMPUTER','PISANG','SEKOLAH']);
Games.scramble=(el,set)=>wordGame(el,set,['NEON','GAMES','CODING','PYTHON','MOBILE']);
Games.math=(el,set)=>{let pts=0,end=Date.now()+30000;el.innerHTML='<div><h2 id="mq"></h2><input id="ma" type="number"><button class="bigbtn" id="mbt">Jawab</button><p class="msg">30 detik</p></div>';let a,b,ans;function q(){a=1+Math.floor(Math.random()*20);b=1+Math.floor(Math.random()*20);ans=a+b;$('#mq').textContent=`${a} + ${b} = ?`;$('#ma').value='';$('#ma').focus()}$('#mbt').onclick=()=>{if(Date.now()>end)return;if(+$('#ma').value===ans){pts++;set(pts*10)}q()};q()};
Games.simon=(el,set)=>{let seq=[],user=0,colors=['🟩','🟦','🟨','🟥'];el.innerHTML='<div><div id="si" class="gamegrid"></div><p id="sm" class="msg">Tekan Mulai</p></div>';let b=$('#si');for(let i=0;i<4;i++)b.append(btn(colors[i],()=>click(i)));let active=false;function next(){seq.push(Math.floor(Math.random()*4));user=0;$('#sm').textContent='Ikuti urutan: '+seq.join(' ')}function click(i){if(!active){active=true;next();return}if(i!==seq[user]){active=false;set((seq.length-1)*20);$('#sm').textContent='Salah! Skor tersimpan.';return}user++;if(user===seq.length){set(seq.length*20);setTimeout(next,400)}}$('#si button:first-child').textContent='🟢 Mulai'};
Games.lights=(el,set)=>{let a=Array(16).fill(0);el.innerHTML='<div><div id="li" class="gamegrid"></div><p class="msg">Matikan semua kotak.</p></div>';function draw(){let b=$('#li');b.innerHTML='';a.forEach((v,i)=>{let q=btn(v?'💡':'·',()=>tap(i));q.style.opacity=v?1:.45;b.append(q)})}function tap(i){[i,i-1,i+1,i-4,i+4].forEach(j=>{if(j>=0&&j<16&&Math.abs((j%4)-(i%4))<=1)a[j]^=1});if(!a.some(Boolean))set(200);draw()}for(let i=0;i<5;i++)tap(Math.floor(Math.random()*16));draw()};
Games.sudoku=(el,set)=>{let ans=[1,2,3,4,3,4,1,2,2,1,4,3,4,3,2,1],a=ans.map((v,i)=>i%3===0?0:v);el.innerHTML='<div><div id="su" class="gamegrid"></div><button class="bigbtn" id="sub">Cek</button><p class="msg">Isi angka 1-4.</p></div>';let b=$('#su');a.forEach((v,i)=>{let q=document.createElement('input');q.value=v||'';q.type='number';q.min=1;q.max=4;q.style.width='100%';q.style.textAlign='center';q.style.background='#1b2233';q.style.color='#fff';q.style.border='2px solid #35405a';q.style.fontSize='22px';if(v)q.disabled=true;q.dataset.i=i;b.append(q)});$('#sub').onclick=()=>{let ok=[...b.children].every((q,i)=>+q.value===ans[i]);if(ok)set(200);alert(ok?'Benar!':'Masih salah.')};
Games.slide=(el,set)=>{let a=[1,2,3,4,5,6,7,8,0];el.innerHTML='<div><div id="sl" class="gamegrid" style="grid-template-columns:repeat(3,1fr)"></div><p class="msg">Klik ubin dekat kotak kosong.</p></div>';for(let z=0;z<30;z++)shuffle();function shuffle(){let e=a.indexOf(0),opts=[e-1,e+1,e-3,e+3].filter(i=>i>=0&&i<9&&Math.abs(i%3-e%3)<=1);let i=opts[Math.floor(Math.random()*opts.length)];[a[e],a[i]]=[a[i],a[e]]}function draw(){let b=$('#sl');b.innerHTML='';a.forEach((v,i)=>{let q=btn(v||'',()=>move(i));q.style.aspectRatio='1';b.append(q)})}function move(i){let e=a.indexOf(0);if(Math.abs(i%3-e%3)+Math.abs(Math.floor(i/3)-Math.floor(e/3))===1){[a[i],a[e]]=[a[e],a[i]];draw();if(a.every((v,i)=>v===(i+1)%9))set(300)}}draw()};
Games.maze=(el,set)=>{el.innerHTML='<div><div id="mz" class="gamegrid"></div><p class="msg">Klik sel untuk bergerak. START → GOAL.</p></div>';let p=0;for(let i=0;i<25;i++){let q=btn(i===0?'S':i===24?'G':'',()=>{if(i===p+1||i===p+5){p=i;set(p*10);draw()}});$('#mz').append(q)}function draw(){[...$('#mz').children].forEach((q,i)=>q.textContent=i===p?'🟢':i===24?'🏁':'')}draw()};
Games.tap=(el,set)=>{let n=0,end;el.innerHTML='<div><button class="bigbtn" id="tp">Mulai</button><p class="msg" id="tpm"></p></div>';$('#tp').onclick=()=>{if(!end){end=Date.now()+10000;$('#tp').textContent='TAP!';let t=setInterval(()=>{if(Date.now()>end){clearInterval(t);$('#tp').disabled=true;$('#tpm').textContent=`Hasil: ${n} tap`;set(n*5)}},100)}n++}};
Games.color=(el,set)=>{let cs=['MERAH','BIRU','HIJAU','KUNING'],pts=0;el.innerHTML='<div><h2 id="ct"></h2><div id="cc"></div><p class="msg">Klik warna sesuai teks.</p></div>';function q(){let c=cs[Math.floor(Math.random()*4)];$('#ct').textContent=c;$('#cc').innerHTML='';cs.forEach(x=>$('#cc').append(btn(x,()=>{if(x===c){pts++;set(pts*10)}q()})))}q()};
Games.quick=(el,set)=>{let pts=0,end=Date.now()+15000;el.innerHTML='<div><div id="qq"></div><p class="msg">Klik target selama 15 detik.</p></div>';function q(){let b=$('#qq');b.innerHTML='';let x=btn('🎯',()=>{if(Date.now()<end){pts++;set(pts*10);q()}});x.style.position='relative';x.style.left=Math.random()*180+'px';x.style.top=Math.random()*80+'px';b.append(x)}q();setTimeout(()=>$('#qq').innerHTML='<b>Selesai!</b>',15000)};
Games.coin=(el,set)=>predict(el,set,'Kepala','Ekor',2);
Games.dice=(el,set)=>predict(el,set,'1','2',6);
function predict(el,set,a,b,n){el.innerHTML=`<div><button class="bigbtn" id="pa">${a}</button><button class="bigbtn" id="pb">${b}</button><p id="pm" class="msg"></p></div>`;let f=v=>{let r=Math.random();let ok=n===2?(r<.5? a:b):(+v===Math.floor(r*n)+1);set(ok?50:0);$('#pm').textContent='Hasil: '+(n===2?(r<.5?a:b):Math.floor(r*n)+1)};$('#pa').onclick=()=>f(n===2?a:1);$('#pb').onclick=()=>f(n===2?b:6)};
Games.higher=(el,set)=>{let card=Math.floor(Math.random()*13)+1,pts=0;el.innerHTML='<div><h2 id="hc"></h2><button class="bigbtn" onclick="window.hf(1)">Lebih Tinggi</button><button class="bigbtn" onclick="window.hf(-1)">Lebih Rendah</button><p class="msg">Kartu saat ini: <b id="hv"></b></p></div>';$('#hv').textContent=card;window.hf=d=>{let n=Math.floor(Math.random()*13)+1;let ok=d===1?n>card:n<card;set(ok?++pts*20:pts*20);card=n;$('#hv').textContent=card;if(!ok)$('#hc').textContent='Salah!'}}; 
Games.blackjack=(el,set)=>{let sum=0;el.innerHTML='<div><h2 id="bj">Total: 0</h2><button class="bigbtn" id="hit">Hit</button><button class="bigbtn" id="stand">Stand</button><p class="msg" id="bjm"></p></div>';function hit(){let n=Math.floor(Math.random()*10)+1;sum+=n;$('#bj').textContent='Total: '+sum;if(sum>21){set(0);$('#bjm').textContent='Bust!';$('#hit').disabled=true}}$('#hit').onclick=hit;$('#stand').onclick=()=>{set(sum<=21?sum*10:0);$('#bjm').textContent=sum<=21?'Berhenti di '+sum+'.':'Bust!'};hit()};
Games.runner=(el,set)=>simpleCanvas(el,set,'runner');
Games.space=(el,set)=>simpleCanvas(el,set,'space');
function wordGame(el,set,words){let w=words[Math.floor(Math.random()*words.length)],scr=w.split('').sort(()=>Math.random()-.5).join(''),pts=0;el.innerHTML=`<div><h2>${scr}</h2><input id="wi"><button class="bigbtn" id="wb">Jawab</button><p class="msg" id="wm"></p></div>`;$('#wb').onclick=()=>{if($('#wi').value.toUpperCase()===w){pts++;set(pts*50);$('#wm').textContent='Benar! Kata baru.';w=words[Math.floor(Math.random()*words.length)];$('#wi').value='';$('h2').textContent=w.split('').sort(()=>Math.random()-.5).join('')}else $('#wm').textContent='Belum benar.'}};
function simpleCanvas(el,set,type){el.innerHTML=`<div><canvas id="cv" width="360" height="260" style="max-width:100%;background:#080b12;border:2px solid #35405a"></canvas><p class="msg">${type==='pong'?'Gerakkan paddle dengan mouse/touch.':type==='break'?'Klik/tap untuk memantulkan bola.':'Klik/tap untuk melompat atau menembak.'}</p></div>`;let c=$('#cv'),x=c.getContext('2d'),t=0,run=1,score=0,px=160,py=220,vx=2,vy=-3;el.onpointermove=e=>{let r=c.getBoundingClientRect();px=(e.clientX-r.left)/r.width*360-25};el.onclick=()=>{vy=-6};function loop(){if(!run)return;t++;x.clearRect(0,0,360,260);x.fillStyle='#65f5d2';x.fillRect(px,py,50,10);x.beginPath();x.arc(180+t%160,80+Math.sin(t/20)*45,8,0,7);x.fill();x.beginPath();x.fillStyle='#ff6384';x.arc(60+t%240,30+((t*2)%180),10,0,7);x.fill();if(type==='runner'){vy+=.25;py+=vy;if(py>220){py=220;vy=0}score++;if(score%20===0)set(Math.floor(score/20))}else if(type==='space'){if(t%15===0){score++;set(score*10)}}else{vx+=0;vy+=.08;let bx=180+t%100,by=80+Math.sin(t/12)*50;if(Math.abs(by-py)<25&&Math.abs(bx-px)<50){score++;set(score*10)}}if(t>2000)run=0;requestAnimationFrame(loop)}loop()}
